#pragma once
#include <vector>
#include <cstdint>
#include <numeric>
#include <execution>

namespace amr {
namespace parallel {

/**
 * @brief Parallel Exclusive Scan (Prefix Sum).
 * * Computes `out[i] = sum(in[0]...in[i-1])`.
 * * Used to determine write offsets for parallel array compaction/expansion 
 * without atomic counters or locks (Burstedde §3.1).
 * * @param in Input vector of counts (e.g., number of children generated by each element).
 * @param out Output vector of offsets.
 */
template <typename T>
void exclusive_scan(const std::vector<T>& in, std::vector<uint64_t>& out) {
    if (in.empty()) return;

    if (out.size() != in.size()) {
        out.resize(in.size());
    }

    // Use par_unseq execution policy for maximum parallelism (SIMD + Threads)
    // Requires linking against TBB (Intel/GCC) or PPL (MSVC).
    std::exclusive_scan(std::execution::par_unseq,
                        in.begin(), in.end(),
                        out.begin(),
                        0ULL);
}

} // namespace parallel
} // namespace amr